[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "cd resources/web && npm ci",
]

[phases.build]
cmds = [
    "cd resources/web && npm run build",
    "mkdir -p storage/framework/cache/data",
    "mkdir -p storage/framework/sessions",
    "mkdir -p storage/framework/views",
    "mkdir -p storage/logs",
    "mkdir -p storage/app/private",
    "mkdir -p storage/app/public",
    "php artisan view:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs storage/app/private storage/app/public && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
