[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "cd resources/web && npm ci",
]

[phases.build]
cmds = [
    "cd resources/web && npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
