[build]
builder = "NIXPACKS"

[build.watchPatterns]
include = ["**/*.php", "**/*.js", "**/*.jsx", "**/*.json", "composer.json", "composer.lock"]

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"
